baseURL = 'http://bcruz.dev/'
languageCode = 'en'
title = 'Brandon Cruz'
theme = "hugo-coder"

[params]
  author = "Brandon Cruz"
  info = "DevOps Engineer and Open Source Enthusiast"
  description = "BCruz-dot-dev"
  keywords = "blog,open-source,personal,devops"
  #avatarurl = "images/avatar.jpg"
  gravatar = "brandonrcruz@gmail.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/brandoncruz3/"
[[params.social]]
  name = "linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/brandonrcruz/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"
[[menu.main]]
  name = "Resume"
  weight = 4
  url  = "resume/"
[[menu.main]]
  name = "Contact"
  weight = 5
  url  = "contact/"
  